# Generated by Django 4.1.3 on 2023-01-12 08:12

import django.core.validators
from django.db import migrations, models
import globalApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(default=None, max_length=100)),
                ('year', models.PositiveIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1984), globalApp.models.MonthDataModel.max_value_current_year])),
                ('dollar_rate', models.IntegerField()),
                ('total_expense', models.IntegerField(default=0)),
                ('per_table_cost', models.FloatField()),
                ('working_day', models.IntegerField()),
                ('per_hrs_fix_cost', models.FloatField()),
            ],
            options={
                'db_table': 'month_global_data_master',
            },
        ),
    ]
