# Generated by Django 4.1.3 on 2023-01-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalApp', '0002_alter_monthdatamodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthdatamodel',
            name='dollar_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
