# Generated by Django 4.1.3 on 2023-01-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalApp', '0003_alter_monthdatamodel_dollar_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthdatamodel',
            name='dollar_rate',
            field=models.FloatField(),
        ),
    ]
