# Generated by Django 4.1.3 on 2022-12-05 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0002_employeemodel_salarymodel_projectmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'employee_type_master',
            },
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='employee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageApp.employeetypemodel'),
        ),
    ]
