# Generated by Django 4.1.3 on 2022-12-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0005_alter_salarymodel_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarymodel',
            old_name='employee',
            new_name='bde_name',
        ),
    ]
