# Generated by Django 4.1.3 on 2022-12-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0008_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
