# Generated by Django 4.1.3 on 2022-12-08 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0009_delete_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarymodel',
            old_name='year',
            new_name='duration',
        ),
    ]
