# Generated by Django 4.1.3 on 2022-12-08 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0010_rename_year_salarymodel_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarymodel',
            old_name='duration',
            new_name='year',
        ),
    ]
