# Generated by Django 4.1.3 on 2022-12-09 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0011_rename_duration_salarymodel_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarymodel',
            old_name='bde_name',
            new_name='employee',
        ),
    ]
