# Generated by Django 4.1.3 on 2022-12-09 10:36

import django.core.validators
from django.db import migrations, models
import manageApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0012_rename_bde_name_salarymodel_employee'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='projectdatamodel',
        #     name='designer_hrs',
        #     field=models.CharField(max_length=255),
        # ),
        # migrations.AlterField(
        #     model_name='projectdatamodel',
        #     name='developer_hrs',
        #     field=models.CharField(max_length=255),
        # ),
        # migrations.AlterField(
        #     model_name='projectdatamodel',
        #     name='month',
        #     field=models.CharField(max_length=100),
        # ),
        # migrations.AlterField(
        #     model_name='projectdatamodel',
        #     name='qa_hrs',
        #     field=models.CharField(max_length=255),
        # ),
        # migrations.AlterField(
        #     model_name='projectdatamodel',
        #     name='total_billable_hrs',
        #     field=models.CharField(max_length=255),
        # ),
        # migrations.AlterField(
        #     model_name='projectdatamodel',
        #     name='total_freeze_hrs',
        #     field=models.CharField(max_length=255),
        # ),
        # migrations.AlterField(
        #     model_name='projectdatamodel',
        #     name='year',
        #     field=models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1984), manageApp.models.ProjectDataModel.max_value_current_year]),
        # ),
    ]
