# Generated by Django 4.1.3 on 2022-12-13 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0013_alter_projectdatamodel_designer_hrs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdatamodel',
            old_name='employee',
            new_name='pm_name',
        ),
        migrations.RenameField(
            model_name='salarymodel',
            old_name='employee',
            new_name='bde_name',
        ),
    ]
