# Generated by Django 4.1.3 on 2022-12-13 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0015_rename_employee_projectmodel_bde_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarymodel',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageApp.employeemodel'),
        ),
    ]
