# Generated by Django 4.1.3 on 2022-12-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0016_alter_salarymodel_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='project_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='project_start_date',
            field=models.DateTimeField(),
        ),
    ]
