# Generated by Django 4.1.3 on 2022-12-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0018_delete_departmentheadcountsummarymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdatamodel',
            name='no_of_active_developer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectdatamodel',
            name='no_of_existing_client',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='projectdatamodel',
            name='no_of_new_client',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='projectdatamodel',
            name='pm_flag',
            field=models.BooleanField(default=False),
        ),
    ]
