# Generated by Django 4.1.3 on 2022-12-20 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0019_projectdatamodel_no_of_active_developer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdatamodel',
            old_name='no_of_existing_client',
            new_name='existing_client_hrs',
        ),
        migrations.RenameField(
            model_name='projectdatamodel',
            old_name='no_of_new_client',
            new_name='new_client_hrs',
        ),
        migrations.RenameField(
            model_name='projectdatamodel',
            old_name='no_of_active_developer',
            new_name='total_active_developer',
        ),
    ]
