# Generated by Django 4.1.3 on 2022-12-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0020_rename_no_of_existing_client_projectdatamodel_existing_client_hrs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='joining_month',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='joining_year',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='relieving_month',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='relieving_year',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
