# Generated by Django 4.1.3 on 2022-12-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0021_employeemodel_joining_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(default='', max_length=255)),
                ('year', models.IntegerField(default=0)),
                ('total_headcount', models.IntegerField(default=0)),
                ('technical_team', models.IntegerField(default=0)),
                ('active_developer', models.IntegerField(default=0)),
                ('total_working_day', models.IntegerField(default=0)),
                ('total_expected_hrs', models.CharField(default=0, max_length=255)),
                ('total_freeze_hrs', models.CharField(default=0, max_length=255)),
                ('new_client_hrs', models.CharField(default=0, max_length=255)),
                ('existing_client_hrs', models.CharField(default=0, max_length=255)),
                ('total_billable_hrs', models.CharField(default=0, max_length=255)),
                ('total_utilization', models.FloatField(default=0)),
                ('total_income', models.IntegerField(default=0)),
                ('total_expense', models.IntegerField(default=0)),
                ('profit', models.FloatField(default=0)),
                ('per_resource_cost', models.FloatField(default=0)),
                ('flag', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'summary_master',
            },
        ),
    ]
