# Generated by Django 4.1.3 on 2022-12-21 07:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import manageApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0022_summarymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmSummaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1984), manageApp.models.PmSummaryModel.max_value_current_year])),
                ('total_freeze_hrs', models.CharField(max_length=255)),
                ('total_billable_hrs', models.CharField(max_length=255)),
                ('existing_client_hrs', models.CharField(default='', max_length=255)),
                ('new_client_hrs', models.CharField(default='', max_length=255)),
                ('no_of_resources', models.IntegerField()),
                ('total_active_developer', models.IntegerField(default=0)),
                ('pm_flag', models.BooleanField(default=False)),
                ('pm_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageApp.employeemodel')),
            ],
            options={
                'db_table': 'pm_summary_master',
            },
        ),
        migrations.DeleteModel(
            name='ProjectDataModel',
        ),
    ]
