# Generated by Django 4.1.3 on 2022-12-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0023_pmsummarymodel_delete_projectdatamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmsummarymodel',
            name='submit_flag',
            field=models.BooleanField(default=False),
        ),
    ]
