# Generated by Django 4.1.3 on 2022-12-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0025_alter_summarymodel_existing_client_hrs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='client',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='project_name',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='project_customer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='project_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
