# Generated by Django 4.1.3 on 2022-12-27 08:46

import django.core.validators
from django.db import migrations, models
import manageApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0026_remove_projectmodel_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarymodel',
            name='month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2022, null=True, validators=[django.core.validators.MinValueValidator(1984), manageApp.models.SalaryModel.max_value_current_year]),
        ),
    ]
