# Generated by Django 4.1.3 on 2022-12-29 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0029_alter_employeemodel_employee_email'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='employeemodel',
        #     unique_together={('employee_email',)},
        # ),
    ]
