# Generated by Django 4.1.3 on 2022-12-29 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0030_alter_employeemodel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeemodel',
            unique_together=set(),
        ),
    ]
