# Generated by Django 4.1.3 on 2022-12-29 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0032_alter_employeemodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='salary_ctc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='status',
            field=models.CharField(choices=[('1', 'Probation'), ('2', 'Confirmed'), ('3', 'Notice'), ('4', 'Terminate'), ('5', 'Relieve')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='expected_hrs',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='mode',
            field=models.CharField(choices=[('1', 'Fixed'), ('2', 'Hourly'), ('3', 'Monthly')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='project_manager',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to='manageApp.employeemodel'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='salarymodel',
            name='payment_mode',
            field=models.CharField(choices=[('1', 'Online'), ('2', 'Default'), ('3', 'F&F')], default='', max_length=100),
        ),
    ]
