# Generated by Django 4.1.3 on 2022-12-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0035_alter_projectmodel_project_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='comments',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='comments',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salarymodel',
            name='comments',
            field=models.CharField(default='', max_length=255),
        ),
    ]
