# Generated by Django 4.1.3 on 2022-12-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0039_alter_projectmodel_project_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='project_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='project_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
