# Generated by Django 4.1.3 on 2022-12-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0040_alter_projectmodel_project_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='project_title',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
