# Generated by Django 4.1.3 on 2023-01-03 13:54

import django.core.validators
from django.db import migrations, models
import manageApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0042_alter_projectmodel_expected_hrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmsummarymodel',
            name='year',
            field=models.PositiveIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1984), manageApp.models.PmSummaryModel.max_value_current_year]),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='project_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='project_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='year',
            field=models.PositiveIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1984), manageApp.models.SalaryModel.max_value_current_year]),
        ),
    ]
