# Generated by Django 4.1.3 on 2023-01-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0043_alter_pmsummarymodel_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='project_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='project_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
