# Generated by Django 4.1.3 on 2023-01-06 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0044_alter_projectmodel_project_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='salarymodel',
            name='comments',
        ),
    ]
