# Generated by Django 4.1.3 on 2023-01-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0045_remove_employeemodel_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salarymodel',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
