# Generated by Django 4.1.3 on 2023-01-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0046_employeemodel_comments_projectmodel_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='salary_ctc',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='payment_mode',
            field=models.CharField(choices=[('1', 'Online'), ('2', 'Default'), ('3', 'F&F')], default='2', max_length=100),
        ),
    ]
