# Generated by Django 4.1.3 on 2023-01-12 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0047_alter_employeemodel_salary_ctc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='project_manager',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to='manageApp.employeemodel'),
        ),
    ]
