# Generated by Django 4.1.3 on 2023-01-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0049_alter_projectmodel_project_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='salary_ctc',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='expected_hrs',
            field=models.CharField(blank=True, default='00:00', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='mode',
            field=models.CharField(blank=True, choices=[('1', 'Fixed'), ('2', 'Hourly'), ('3', 'Monthly')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Active'), ('2', 'Inactive')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='month',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('1', 'Online'), ('2', 'Default'), ('3', 'F&F')], default='2', max_length=100),
        ),
        # migrations.AlterField(
        #     model_name='salarymodel',
        #     name='salary',
        #     field=models.FloatField(default=''),
        # ),
    ]
