# Generated by Django 4.1.3 on 2023-01-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0050_alter_employeemodel_salary_ctc_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='salarymodel',
        #     name='salary',
        #     field=models.FloatField(default='0', null=True),
        # ),
    ]
