# Generated by Django 4.1.3 on 2023-01-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0052_alter_salarymodel_salary'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='salarymodel',
        #     name='salary',
        #     field=models.FloatField(blank=True, default=None, null=True),
        # ),
    ]
