# Generated by Django 4.1.3 on 2023-01-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0055_salarymodel_per_hrs_cost_dollar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='per_hrs_rate_dollar',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='per_hrs_rate_inr',
            field=models.FloatField(default='0'),
        ),
    ]
