# Generated by Django 4.1.3 on 2023-01-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0057_alter_departmentmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarymodel',
            name='per_hrs_cost_dollar',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=5),
        ),
    ]
