# Generated by Django 4.1.3 on 2023-01-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0058_alter_salarymodel_per_hrs_cost_dollar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='per_hrs_rate_dollar',
            field=models.FloatField(default='0'),
        ),
    ]
