# Generated by Django 4.1.3 on 2023-01-13 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0059_alter_invoicemodel_per_hrs_rate_dollar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=255)),
                ('year', models.IntegerField(default=0)),
                ('billable_hrs', models.CharField(default='00:00', max_length=255)),
                ('spent_hrs', models.CharField(default='00:00', max_length=255)),
                ('per_hrs_cost_inr', models.FloatField(default='0.0')),
                ('per_hrs_cost_dollar', models.FloatField(default='0.0')),
                ('per_hrs_rate_inr', models.FloatField(default='0.0')),
                ('per_hrs_rate_dollar', models.FloatField(default='0.0')),
                ('total_cost_inr', models.FloatField(default='0.0')),
                ('total_rate_inr', models.FloatField(default='0.0')),
                ('total_cost_dollar', models.FloatField(default='0.0')),
                ('total_rate_dollar', models.FloatField(default='0.0')),
                ('profit', models.FloatField(default='0.0')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageApp.employeemodel')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageApp.projectmodel')),
                ('resource_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_name', to='manageApp.employeemodel')),
            ],
            options={
                'verbose_name': 'Project Details Model',
                'db_table': 'project_details_master',
            },
        ),
    ]
