# Generated by Django 4.1.3 on 2023-01-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0060_projectdetailsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarymodel',
            name='per_hrs_cost_dollar',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='per_hrs_cost_inr',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
    ]
